# Generated by Django 2.2.24 on 2021-09-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject_day', models.CharField(max_length=50)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('students', models.ManyToManyField(related_name='subjects', to='students.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teachers.Teacher')),
            ],
        ),
    ]
